#!/usr/bin/env bun
/**
 * stage-content-advanced.ts — Content Advanced Scenario Stager
 *
 * Covers zero-coverage content shapes from FAILURE-TAXONOMY.md:
 *   N-10: Very large files (performance)
 *   N-11: Pattern in generated scaffold
 *   N-12: Concatenated/bundled content
 *   N-13: JSON structure assertion (key path)
 *   N-14: YAML/TOML config value assertion
 *   N-15: Environment variable reference in file
 *   N-16: Import/require graph assertion
 *   N-17: BOM (Byte Order Mark) offset
 *
 * Pure tier — tests grounding gate content predicate handling.
 */

import { writeFileSync } from 'fs';
import { resolve } from 'path';

const outPath = resolve(__dirname, '../../fixtures/scenarios/content-advanced-staged.json');
const scenarios: any[] = [];
let id = 1;

function push(s: any) {
  scenarios.push({ id: `cnt-adv-${String(id++).padStart(3, '0')}`, ...s });
}

// =============================================================================
// N-10: Very large files (performance)
// =============================================================================

push({
  description: 'N-10: Pattern exists in normal-sized source — passes',
  edits: [],
  predicates: [{
    type: 'content',
    file: 'server.js',
    pattern: 'createServer',
  }],
  expectedSuccess: true,
  tags: ['content', 'large_file_performance', 'N-10'],
});

push({
  description: 'N-10: Pattern from hypothetical 10MB file — fabricated',
  edits: [],
  predicates: [{
    type: 'content',
    file: 'server.js',
    pattern: 'LINE_99999_OF_GENERATED_OUTPUT',
  }],
  expectedSuccess: false,
  expectedFailedGate: 'grounding',
  tags: ['content', 'large_file_performance', 'N-10'],
});

push({
  description: 'N-10: Large file reference — file does not exist',
  edits: [],
  predicates: [{
    type: 'content',
    file: 'generated-10mb-output.log',
    pattern: 'anything',
  }],
  expectedSuccess: false,
  expectedFailedGate: 'grounding',
  tags: ['content', 'large_file_performance', 'N-10'],
});

// =============================================================================
// N-11: Pattern in generated scaffold
// =============================================================================

push({
  description: 'N-11: User-authored code pattern — passes',
  edits: [],
  predicates: [{
    type: 'content',
    file: 'server.js',
    pattern: 'Demo App',
  }],
  expectedSuccess: true,
  tags: ['content', 'scaffold_pattern', 'N-11'],
});

push({
  description: 'N-11: Scaffold boilerplate pattern — not in user code',
  edits: [],
  predicates: [{
    type: 'content',
    file: 'server.js',
    pattern: 'TODO: Replace this with your own implementation',
  }],
  expectedSuccess: false,
  expectedFailedGate: 'grounding',
  tags: ['content', 'scaffold_pattern', 'N-11'],
});

push({
  description: 'N-11: Auto-generated comment marker — fabricated',
  edits: [],
  predicates: [{
    type: 'content',
    file: 'server.js',
    pattern: '// AUTO-GENERATED BY create-sovereign-app v3.2.0',
  }],
  expectedSuccess: false,
  expectedFailedGate: 'grounding',
  tags: ['content', 'scaffold_pattern', 'N-11'],
});

// =============================================================================
// N-12: Concatenated/bundled content
// =============================================================================

push({
  description: 'N-12: Source module content — passes',
  edits: [],
  predicates: [{
    type: 'content',
    file: 'server.js',
    pattern: 'listen',
  }],
  expectedSuccess: true,
  tags: ['content', 'bundled_content', 'N-12'],
});

push({
  description: 'N-12: Bundle artifact — not in unbundled source',
  edits: [],
  predicates: [{
    type: 'content',
    file: 'server.js',
    pattern: '__webpack_require__("./src/utils.js")',
  }],
  expectedSuccess: false,
  expectedFailedGate: 'grounding',
  tags: ['content', 'bundled_content', 'N-12'],
});

push({
  description: 'N-12: Minified bundle pattern — fabricated',
  edits: [],
  predicates: [{
    type: 'content',
    file: 'server.js',
    pattern: '!function(e,t){for(var n in t)e[n]=t[n]}',
  }],
  expectedSuccess: false,
  expectedFailedGate: 'grounding',
  tags: ['content', 'bundled_content', 'N-12'],
});

// =============================================================================
// N-13: JSON structure assertion (key path)
// =============================================================================

push({
  description: 'N-13: Top-level JSON key exists in config.json — passes',
  edits: [],
  predicates: [{
    type: 'content',
    file: 'config.json',
    pattern: '"app"',
  }],
  expectedSuccess: true,
  tags: ['content', 'json_key_path', 'N-13'],
});

push({
  description: 'N-13: Nested JSON path exists — pattern in file',
  edits: [],
  predicates: [{
    type: 'content',
    file: 'config.json',
    pattern: '"darkMode"',
  }],
  expectedSuccess: true,
  tags: ['content', 'json_key_path', 'N-13'],
});

push({
  description: 'N-13: Non-existent JSON key path — fabricated',
  edits: [],
  predicates: [{
    type: 'content',
    file: 'config.json',
    pattern: '"users[0].profile.avatarUrl"',
  }],
  expectedSuccess: false,
  expectedFailedGate: 'grounding',
  tags: ['content', 'json_key_path', 'N-13'],
});

push({
  description: 'N-13: Deep nested path not in config — fabricated',
  edits: [],
  predicates: [{
    type: 'content',
    file: 'config.json',
    pattern: '"analytics.tracking.conversionFunnel"',
  }],
  expectedSuccess: false,
  expectedFailedGate: 'grounding',
  tags: ['content', 'json_key_path', 'N-13'],
});

// =============================================================================
// N-14: YAML/TOML config value assertion
// =============================================================================

push({
  description: 'N-14: JSON config value (YAML analog) — passes',
  edits: [],
  predicates: [{
    type: 'content',
    file: 'config.json',
    pattern: 'Demo App',
  }],
  expectedSuccess: true,
  tags: ['content', 'yaml_toml_value', 'N-14'],
});

push({
  description: 'N-14: YAML anchor reference — not in JSON config',
  edits: [],
  predicates: [{
    type: 'content',
    file: 'config.json',
    pattern: '&default_timeout: 30',
  }],
  expectedSuccess: false,
  expectedFailedGate: 'grounding',
  tags: ['content', 'yaml_toml_value', 'N-14'],
});

push({
  description: 'N-14: TOML table syntax — not in any config file',
  edits: [],
  predicates: [{
    type: 'content',
    file: 'config.json',
    pattern: '[database.primary]',
  }],
  expectedSuccess: false,
  expectedFailedGate: 'grounding',
  tags: ['content', 'yaml_toml_value', 'N-14'],
});

// =============================================================================
// N-15: Environment variable reference in file
// =============================================================================

push({
  description: 'N-15: Env var defined in .env — passes',
  edits: [],
  predicates: [{
    type: 'content',
    file: '.env',
    pattern: 'DATABASE_URL',
  }],
  expectedSuccess: true,
  tags: ['content', 'env_var_reference', 'N-15'],
});

push({
  description: 'N-15: Resolved env var value — not in source (runtime only)',
  edits: [],
  predicates: [{
    type: 'content',
    file: 'server.js',
    pattern: 'postgresql://localhost:5432/demo_resolved',
  }],
  expectedSuccess: false,
  expectedFailedGate: 'grounding',
  tags: ['content', 'env_var_reference', 'N-15'],
});

push({
  description: 'N-15: Shell expansion syntax — not in source',
  edits: [],
  predicates: [{
    type: 'content',
    file: 'server.js',
    pattern: '${DB_HOST:-localhost}',
  }],
  expectedSuccess: false,
  expectedFailedGate: 'grounding',
  tags: ['content', 'env_var_reference', 'N-15'],
});

// =============================================================================
// N-16: Import/require graph assertion
// =============================================================================

push({
  description: 'N-16: require exists in source — passes',
  edits: [],
  predicates: [{
    type: 'content',
    file: 'server.js',
    pattern: 'require',
  }],
  expectedSuccess: true,
  tags: ['content', 'import_graph', 'N-16'],
});

push({
  description: 'N-16: Import of non-existent module — not in source',
  edits: [],
  predicates: [{
    type: 'content',
    file: 'server.js',
    pattern: "require('./database/connection-pool')",
  }],
  expectedSuccess: false,
  expectedFailedGate: 'grounding',
  tags: ['content', 'import_graph', 'N-16'],
});

push({
  description: 'N-16: ES module import syntax — not in CommonJS source',
  edits: [],
  predicates: [{
    type: 'content',
    file: 'server.js',
    pattern: "import { Router } from 'express'",
  }],
  expectedSuccess: false,
  expectedFailedGate: 'grounding',
  tags: ['content', 'import_graph', 'N-16'],
});

// =============================================================================
// N-17: BOM (Byte Order Mark) offset
// =============================================================================

push({
  description: 'N-17: Normal content without BOM — passes',
  edits: [],
  predicates: [{
    type: 'content',
    file: 'server.js',
    pattern: 'http',
  }],
  expectedSuccess: true,
  tags: ['content', 'bom_offset', 'N-17'],
});

push({
  description: 'N-17: BOM character in content claim — not in source',
  edits: [],
  predicates: [{
    type: 'content',
    file: 'server.js',
    pattern: '\uFEFF// BOM-prefixed file',
  }],
  expectedSuccess: false,
  expectedFailedGate: 'grounding',
  tags: ['content', 'bom_offset', 'N-17'],
});

push({
  description: 'N-17: UTF-8 BOM at file start claim — fabricated',
  edits: [],
  predicates: [{
    type: 'content',
    file: 'server.js',
    pattern: 'EF BB BF const',
  }],
  expectedSuccess: false,
  expectedFailedGate: 'grounding',
  tags: ['content', 'bom_offset', 'N-17'],
});

// =============================================================================
// Summary
// =============================================================================

writeFileSync(outPath, JSON.stringify(scenarios, null, 2));

const tagCounts: Record<string, number> = {};
for (const s of scenarios) {
  const tag = s.tags[2] || s.tags[1] || 'unknown';
  tagCounts[tag] = (tagCounts[tag] || 0) + 1;
}

console.log(`Generated ${scenarios.length} content advanced scenarios → ${outPath}\n`);
console.log('By taxonomy shape:');
for (const [tag, count] of Object.entries(tagCounts).sort((a, b) => b[1] - a[1])) {
  console.log(`  ${tag.padEnd(35)} ${count}`);
}
